dist: bionic
os:
  - linux
language: python
python:
  - "3.7"

addons:
  apt:
      packages: ['python3.7', 'python3-pip', 'git']

install:
  - pip3 install -r requirements.txt
  - git clone https://github.com/xingweitian/mkdocs-rtd-dropdown.git && cd mkdocs-rtd-dropdown && python3 setup.py install

deploy:
  provider: script
  script: mkdocs gh-deploy
  on:
    branch: master
